blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_la_web_app_id
     ***REMOVED***
  usermanagementservice:
    servicehost:
      host: localhost
      port: 8180
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/user-management-service/1.0.0
  badgemanagementservice:
    servicehost:
      host: localhost
      port: 8280
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/badge-management-service/1.0.0
  referencedataservice:
    servicehost:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
  applicationsservice:
    servicehost:
      host: localhost
      port: 8680
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/application-management-service/1.0.0
  client-time-zone: Europe/London

logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.webapp: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: DEBUG

management:
  server:
    port: 8081
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
  profiles:
    active: dev
      # include: static/css/**,static/js/**

server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    #max-swallow-size: -1

security:
  oauth2:
    client:
      client-id: ${blue-badge.auth-server.client-id}
       ***REMOVED***
      access-token-uri: ${blue-badge.auth-server.url}/oauth/token
      user-authorization-uri: ${blue-badge.auth-server.url}/oauth/authorize
      # All scopes approve, else user redirect to auth server to approve the protected resource
      auto-approve-scopes: '.*'
    resource:
      user-info-uri: ${blue-badge.auth-server.url}/me
