logging:
  level:
    uk.gov.dft.bluebadge: DEBUG

management:
  server:
    port: 8081
    address: localhost
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
      # include: static/css/**,static/js/**

server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

usermanagementservice:
  servicehost:
    host: localhost
    port: 8180
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/user-management-service/1.0.0

badgemanagementservice:
  servicehost:
    host: localhost
    port: 8280
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/badge-management-service/1.0.0

