blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_la_web_app_id
     ***REMOVED***
  usermanagementservice:
    servicehost:
      host: usermanagement-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/user-management-service/1.0.0
  badgemanagementservice:
    servicehost:
      host: badge-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/badge-management-service/1.0.0
  referencedataservice:
    servicehost:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
  applicationsservice:
    servicehost:
      host: application-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/application-management-service/1.0.0
  client-time-zone: Europe/London
logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.webapp: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: DEBUG

management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
      # include: static/css/**,static/js/**
    redis:
      host: redis.elasticache-admin.${bb_env}.${url}

server:
  port: ${bb_port:-8080}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

security:
  oauth2:
    client:
      client-id: ${blue-badge.auth-server.client-id}
       ***REMOVED***
      access-token-uri: ${blue-badge.auth-server.url}/oauth/token
      user-authorization-uri: ${blue-badge.auth-server.url}/oauth/authorize
      # All scopes approve, else user redirect to auth server to approve the protected resource
      auto-approve-scopes: '.*'
    resource:
      user-info-uri: ${blue-badge.auth-server.url}/me
 
 # Google Analytics Code
GACode:  ${GACODE:UA-124760983-5}
