bbb:
  auth-server-url: http://localhost:8380/bbb_auth

logging:
  level:
    uk.gov.dft.bluebadge: DEBUG
    org.springframework.security: DEBUG

management:
  server:
    port: 8081
    address: localhost
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
#spring.devtools.restart.include=static/css/**,static/js/**

server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

security:
  oauth2:
    client:
      client-id: bbb_test_web_app_id
       ***REMOVED***
      access-token-uri: ${bbb.auth-server-url}/oauth/token
      user-authorization-uri: ${bbb.auth-server-url}/oauth/authorize
      # All scopes approve, else user redirect to auth server to approve the protected resource
      auto-approve-scopes: '.*'
    resource:
      user-info-uri: ${bbb.auth-server-url}/me
