blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_la_web_app_id
     ***REMOVED***
  usermanagementservice:
    servicehost:
      host: usermanagement-service.${bb_env}.${url}
      port: 443
      scheme: https
  badgemanagementservice:
    servicehost:
      host: badge-service.${bb_env}.${url}
      port: 443
      scheme: https
  referencedataservice:
    servicehost:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
  applicationsservice:
    servicehost:
      host: application-service.${bb_env}.${url}
      port: 443
      scheme: https

management:
  server:
    port: ${bb_health:-8081}

spring:
  main:
    banner-mode: "off"
  redis:
    host:
    cluster:
      nodes: redis.elasticache-admin.${asg}.${bb_env}.${url}:6379
  resources:
    cache:
      cachecontrol:
        max-age: 315360000
        no-store: false

server:
  port: ${bb_port:-8080}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

 # Google Analytics Code
GACode:  ${GACODE:UA-124760983-5}
