bbb:
  auth-server-url: http://localhost:8380/bbb_auth

logging:
  level:
    uk.gov.dft.bluebadge: DEBUG
    org.springframework.security: INFO

management:
  server:
    port: 8081
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
      # include: static/css/**,static/js/**

server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

usermanagementservice:
  servicehost:
    host: localhost
    port: 8180
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/user-management-service/1.0.0

badgemanagementservice:
  servicehost:
    host: localhost
    port: 8280
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/badge-management-service/1.0.0

security:
  oauth2:
    client:
      client-id: bbb_test_web_app_id
       ***REMOVED***
      access-token-uri: ${bbb.auth-server-url}/oauth/token
      user-authorization-uri: ${bbb.auth-server-url}/oauth/authorize
      # All scopes approve, else user redirect to auth server to approve the protected resource
      auto-approve-scopes: '.*'
    resource:
      user-info-uri: ${bbb.auth-server-url}/me
