blue-badge:
  auth-server:
    url: http://authorisation-service:8080/bb_auth
  usermanagementservice:
    servicehost:
      host: usermanagement-service
  badgemanagementservice:
    servicehost:
      host: badgemanagement-service
