blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
  usermanagementservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /user
  badgemanagementservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /badges
  referencedataservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /reference-data
  applicationsservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /applications

management:
  server:
    port: ${bb_health:-8081}

spring:
  main:
    banner-mode: "off"
  redis:
    host:
    ssl: true
    cluster:
      nodes: ${REDIS_HOSTNAME}:6379
  resources:
    static-locations: classpath:/static/
    cache:
      cachecontrol:
        no-store: false
        max-age: 315360000

server:
  port: ${bb_port:-8080}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

 # Google Analytics Code
GACode:  ${GACODE:UA-124760983-5}
