blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
  usermanagementservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
  badgemanagementservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
  referencedataservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
  applicationsservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /

management:
  server:
    port: ${bb_health:8081}

spring:
  main:
    banner-mode: "off"
  redis:
    host:
    ssl: true
    cluster:
      nodes: ${REDIS_HOSTNAME}:6379
  resources:
    static-locations: classpath:/static/
    cache:
      cachecontrol:
        no-store: false
        max-age: 315360000

server:
  port: ${bb_port:8080}

 # Google Analytics Code
GACode:  ${GACODE}
